# type: ignore
"""init

Revision ID: b5950647bd2a
Revises:
Create Date: 2024-02-23 11:30:01.454462+00:00

"""
from __future__ import annotations

import warnings

import sqlalchemy as sa
from advanced_alchemy.types import GUID, ORA_JSONB, DateTimeUTC, EncryptedString, EncryptedText
from alembic import op
from sqlalchemy import Text  # noqa: F401

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "b5950647bd2a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("language_name", sa.String(length=40), nullable=False),
        sa.Column("parser_name", sa.String(length=40), nullable=True),
        sa.Column("RTL", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_languages")),
    )
    op.create_table(
        "words",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("word_string", sa.String(length=100), nullable=False),
        sa.Column("word_lemma", sa.String(length=100), nullable=True),
        sa.Column("word_pos", sa.String(length=100), nullable=True),
        sa.Column("is_multiple_words", sa.Boolean(), nullable=False),
        sa.Column("word_status", sa.Integer(), nullable=False),
        sa.Column("word_pronunciation", sa.String(length=100), nullable=True),
        sa.Column("word_explanation", sa.String(length=100), nullable=True),
        sa.Column("word_counts", sa.Integer(), nullable=True),
        sa.Column("word_tokens", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
        sa.UniqueConstraint("word_string", name=op.f("uq_words_word_string")),
    )
    op.create_table(
        "books",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("book_name", sa.String(length=300), nullable=False),
        sa.Column("language_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"], name=op.f("fk_books_language_id_languages")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
    )
    op.create_table(
        "word_images",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("word_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("word_image_name", sa.String(length=100), nullable=False),
        sa.Column("word_image_path", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["word_id"], ["words.id"], name=op.f("fk_word_images_word_id_words")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_word_images")),
    )
    op.create_table(
        "booktexts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("ref_book_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("book_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["ref_book_id"], ["books.id"], name=op.f("fk_booktexts_ref_book_id_books")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booktexts")),
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booktexts")
    op.drop_table("word_images")
    op.drop_table("books")
    op.drop_table("words")
    op.drop_table("languages")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
